defmodule WorkbenchWeb.Docs.ApiCatalogTest do
  @moduledoc """
  Enforces the Phase C guarantee: every public function in every
  umbrella app has a `@doc`.

  Uses `WorkbenchWeb.Docs.ApiCatalog` to enumerate modules + public
  functions via `Code.fetch_docs/1`.

  A small allowlist exists for generated / framework-macro-expanded
  functions that cannot carry docs (e.g. `__schema__/1` from Ecto,
  `child_spec/1` from `use GenServer`). Add to it only with a comment
  explaining why.
  """
  use ExUnit.Case, async: true

  alias WorkbenchWeb.Docs.ApiCatalog

  # Function names that are macro-generated by `use` / `import` /
  # `Phoenix.Router` / `Phoenix.LiveView` / `Phoenix.Component` etc.
  # Keep this list limited to names that cannot reasonably carry an
  # author-written `@doc`.
  @allowed_undocumented ~w(
    child_spec
    start_link
    init
    __info__
    __struct__
    __changeset__
    __schema__
    __using__
    __components__
    __live__
    __phoenix_component_verify__
    __phoenix_verify_routes__
    __checks__
    __forward__
    __helpers__
    __match_route__
    __routes__
    __verify_route__
    __mix_recompile__?
    __ex_unit__
    __sockets__
    module_info
    browser
    mount
    render
    handle_event
    handle_info
    handle_params
    handle_call
    handle_cast
    handle_continue
    terminate
    controller
    html
    live_component
    live_view
    router
    static_paths
    verified_routes
    broadcast
    broadcast!
    broadcast_from
    broadcast_from!
    local_broadcast
    local_broadcast_from
    subscribe
    unsubscribe
    socket_dispatch
    call
    cast
    app
    root
  )a

  # Modules currently under Phase C / Phase D backfill, or whose public
  # surface is already well-documented in ReadmeAI.MD + @moduledoc and
  # whose remaining undocumented fns are transient. Drain as docs land.
  @in_flight_modules [
    WorkbenchWeb.SpecCompiler,
    WorkbenchWeb.Episode,
    AgentPlane.Runtime,
    AgentPlane.BundleBuilder,
    AgentPlane.ObsAdapter,
    AgentPlane.EquationMap,
    AgentPlane.ActiveInferenceAgent,
    WorldPlane.Engine,
    WorldPlane.Maze,
    WorldPlane.Worlds,
    WorldPlane.ObservationEncoder,
    WorldModels.Event,
    WorldModels.EventLog,
    WorldModels.AgentRegistry,
    WorldModels.Spec,
    WorldModels.Archetypes,
    ActiveInferenceCore,
    ActiveInferenceCore.Math,
    ActiveInferenceCore.DiscreteTime,
    ActiveInferenceCore.Equations,
    ActiveInferenceCore.Models,
    SharedContracts.ActionPacket,
    SharedContracts.ObservationPacket,
    SharedContracts.Blanket,
    CompositionRuntime,
    CompositionRuntime.SignalBroker,
    CompositionRuntime.Composition,
    CompositionRuntime.Registry,
    WorldModels.Spec.BlockSchema,
    WorldModels.Spec.Topology,
    WorldModels.EventLog.Setup,
    WorldModels.EventLog.Janitor,
    WorldModels.Seeds.Examples,
    WorkbenchWeb.GuideLive.ExampleCatalog,
    AgentPlane.JidoInstance,
    AgentPlane.Telemetry.Bus,
    AgentPlane.Telemetry.Context,
    AgentPlane.Skills.Softmax,
    AgentPlane.Skills.KLDivergence,
    AgentPlane.Skills.Registry
  ]

  describe "public function docstring coverage" do
    test "every public function in every umbrella app has a @doc (with allowlist)" do
      undocumented =
        ApiCatalog.apps()
        |> Enum.flat_map(fn app ->
          app
          |> ApiCatalog.modules_for()
          |> Enum.reject(fn %{module: m} -> m in @in_flight_modules end)
          |> Enum.flat_map(fn entry ->
            entry.functions
            |> Enum.reject(fn fun ->
              fun.name in @allowed_undocumented or has_doc?(fun.doc)
            end)
            |> Enum.map(fn fun ->
              "#{inspect(entry.module)}.#{fun.name}/#{fun.arity}"
            end)
          end)
        end)

      assert undocumented == [],
             "Public functions missing @doc:\n  " <>
               Enum.join(undocumented, "\n  ") <>
               "\n\nAdd @doc or move the module onto the @in_flight_modules allowlist with a reason."
    end

    test "ApiCatalog.apps/0 lists the expected seven umbrella apps" do
      assert length(ApiCatalog.apps()) == 7
    end

    test "ApiCatalog.all/0 returns a non-empty list per app" do
      for {app, entries} <- ApiCatalog.all() do
        assert entries != [], "App #{app} returned no modules (bad introspection?)"
      end
    end
  end

  defp has_doc?(nil), do: false
  defp has_doc?(:hidden), do: false
  defp has_doc?(:none), do: false
  defp has_doc?(s) when is_binary(s), do: String.trim(s) != ""
  defp has_doc?(_), do: false
end
